### ISSUE TITLE
go install fails on arm64

### ISSUE THREAD

**Issue by jagsta** [katalix/go-l2tp#9]
Hi, I am able to install successfully on amd64, but on arm64 architecture I get the following errors:

# github.com/katalix/go-l2tp/cmd/kl2tpd
./pppbridge.go:19:18: undefined: socketPPPoE
./pppbridge.go:30:21: undefined: socketPPPoL2TPv4
./pppd.go:72:13: undefined: socketPPPoL2TPv4

I've tried cross-compiling on amd64 for arm64 target with the same result.

**Comment by jagsta** [comment]
I'm hoping to run kl2tpd as a replacement for xl2tpd on openWRT to provide ipv6 tunnel endpoint support!

**Comment by tomparkin** [comment]
Hi @jagsta, thanks for reporting this issue.

I have not cross-compiled go-l2tp myself, but the debian packaging is successfully building it for a range of architectures[1] including arm64 so in theory at least it should work!

Can I ask which version of the code you're building and how you're building it?

[1]. https://packages.debian.org/search?keywords=go-l2tp&searchon=names&suite=all&section=all

**Comment by jagsta** [comment]
Ah that's interesting!

I've attempted to build on openWRT (23.05) on aarch64/arm64 which uses go 1.21, which is where I first saw the error, using the install instructions in the Readme.MD (go install github.com/katalix/go-l2tp/...@latest)

When that failed, I tried on an ubuntu machine, which is AMD64, go 1.23. This installed fine, but attempting to cross compile for arm64 produced the same errors.

It should be said i'm a total novice with go installation/compilation, so it could be something silly on my part which is causing the problem. I wonder if I can take the compiled arm64 kl2tpd binary from the debian release to try on my openWRT system?

**Comment by jagsta** [comment]
It's dynamically linked, so is missing the right shared library on my openWRT install unfortunately

**Comment by tomparkin** [comment]
This looks as though it may be a cgo thing :-(

Due to the go runtime not supporting the PPPoE socket types, go-l2tp uses cgo[1] to directly call the C API for managing these sockets.  It's worth noting that we added L2TPIP socket support directly to the go runtime, I don't recall now whether that wasn't possible using cgo -- but in any case, go-l2tp is currently using cgo for PPPoL2TP and PPPoE sockets.

There is apparently a magic variable you can set when cross-compiling to enable cgo[2].

Sadly this flat-out doesn't work out the box here:

```
tom@magpie:~/src/go-l2tp$ CGO_ENABLED=1 GOOS=linux GOARCH=arm64 go build -v ./... 
runtime/cgo
# runtime/cgo
gcc_arm64.S: Assembler messages:
gcc_arm64.S:30: Error: no such instruction: `stp x29,x30,[sp,'
gcc_arm64.S:34: Error: operand size mismatch for `mov'
gcc_arm64.S:36: Error: no such instruction: `stp x19,x20,[sp,'
gcc_arm64.S:39: Error: no such instruction: `stp x21,x22,[sp,'
gcc_arm64.S:42: Error: no such instruction: `stp x23,x24,[sp,'
gcc_arm64.S:45: Error: no such instruction: `stp x25,x26,[sp,'
gcc_arm64.S:48: Error: no such instruction: `stp x27,x28,[sp,'
gcc_arm64.S:52: Error: operand size mismatch for `mov'
gcc_arm64.S:53: Error: operand size mismatch for `mov'
gcc_arm64.S:54: Error: operand size mismatch for `mov'
gcc_arm64.S:56: Error: no such instruction: `blr x20'
gcc_arm64.S:57: Error: no such instruction: `blr x19'
gcc_arm64.S:59: Error: no such instruction: `ldp x27,x28,[sp,'
gcc_arm64.S:62: Error: no such instruction: `ldp x25,x26,[sp,'
gcc_arm64.S:65: Error: no such instruction: `ldp x23,x24,[sp,'
gcc_arm64.S:68: Error: no such instruction: `ldp x21,x22,[sp,'
gcc_arm64.S:71: Error: no such instruction: `ldp x19,x20,[sp,'
gcc_arm64.S:74: Error: no such instruction: `ldp x29,x30,[sp],'
```

So I expect one needs to set up some extra cross-compilation support.  It may be worth looking at how Debian is doing things (I did the work for the Debian packaging, but the nuts and bolts were dealt with via the many Debian packaging tools and wrappers so I didn't get exposed to cross compilation at all).

[1]. https://pkg.go.dev/cmd/cgo
[2]. https://www.slingacademy.com/article/cross-compiling-go-programs-for-any-os/#advanced-cross-compiling-options

**Comment by jagsta** [comment]
That's been a massive help! After installing the aarch64 gcc cross compiler the following works:

```
jagb@nuc:~/go/pkg/mod/github.com/katalix/go-l2tp@v0.1.8$ CGO_ENABLED=1 CC=aarch64-linux-gnu-gcc GOOS=linux GOARCH=arm64 go build -v ./...
runtime/cgo
net
github.com/katalix/go-l2tp/pppoe
github.com/mdlayher/netlink
github.com/mdlayher/genetlink
github.com/katalix/go-l2tp/internal/nll2tp
github.com/katalix/go-l2tp/l2tp
github.com/katalix/go-l2tp/config
github.com/katalix/go-l2tp/cmd/ql2tpd
github.com/katalix/go-l2tp/cmd/kpppoed
github.com/katalix/go-l2tp/cmd/kl2tpd
```

**Comment by jagsta** [comment]
Final comment in case it's useful to anyone trying the same thing, the above command results in a dynamically linked executable. To get a statically linked one, you need to include flags for the external linker thus:

`CGO_ENABLED=1 CC=aarch64-linux-gnu-gcc GOOS=linux GOARCH=arm64 go build -ldflags '-extldflags "-static"' -o ~/go/bin/ -v ./...`

Finally, to instal the correct cross compiler on ubuntu:

`sudo apt install gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu`
